# Secret Scanning Configuration
# This file tells GitHub to ignore certain patterns that are false positives

# If you have test/example credentials that are not real secrets, 
# you can add patterns here. However, it's better to remove real
# secrets from the codebase entirely.

# Example (uncomment if needed):
# paths:
#   - "**/*.example"
#   - "**/test/**"
#   - "**/mock/**"
